title: Athena Project
email: webcom@ucf.edu
description: >
    Documentation site for the various Athena Project products.
baseurl: ""
markdown: kramdown
gems:
    - jekyll-feed
exclude: 
    - node_modules
    - gulpfile.js
    - package.json
    - bower_components
    - Gemfile
    - Gemfile.lock